apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: 'http'
      nodePort: 31000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: NodePort
