apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '50051'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - image: faemeister/nest-todo_todo
          name: nest-todo-todo-8hglp
          ports:
            - containerPort: 50051
            - containerPort: 3000
            - containerPort: 9999
          envFrom:
            - secretRef:
                name: databaseurl
          env:
            - name: 'PROMETHEUS_METRIC_PATH'
              value: '/metrics'
            - name: 'TODO_SERVICE_HOST'
              value: '0.0.0.0'
            - name: 'TODO_SERVICE_PORT'
              value: '50051'
            - name: 'TODO_SERVICE_HTTP_PORT'
              value: '3000'
