apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo
  name: todo
spec:
  ports:
    - name: 'todorpc'
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: todo
