apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '50051'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - image: faemeister/nest-todo_auth
          name: nest-todo-auth
          ports:
            - containerPort: 50051
            - containerPort: 3000
            - containerPort: 9999
          envFrom:
            - secretRef:
                name: databaseurl
            - secretRef:
                name: jwtsecret
          env:
            - name: 'PROMETHEUS_METRIC_PATH'
              value: '/metrics'
            - name: 'AUTH_SERVICE_HOST'
              value: '0.0.0.0'
            - name: 'AUTH_SERVICE_PORT'
              value: '50051'
            - name: 'AUTH_SERVICE_HTTP_PORT'
              value: '3000'
