apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: 'authrpc'
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: 'auth-http'
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 'auth-health'
      port: 9999
      protocol: TCP
      targetPort: 9999
