apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: 'authrpc'
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: auth
