apiVersion: v1
kind: Service
metadata:
  labels:
    app: canva
  name: canva
spec:
  ports:
    - name: 'canvarpc'
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: 'canva-http'
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 'canva-health'
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: canva
