apiVersion: v1
kind: Service
metadata:
  labels:
    app: canva
  name: canva
spec:
  ports:
    - name: 'canvarpc'
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: canva
